//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbmodel11
{
    using System;
    using System.Collections.Generic;
    
    public partial class CastingDirector
    {
        public int PKCD_ID { get; set; }
        public int AdminPKAmin_ID { get; set; }
        public int LoginLogin_ID { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Login Login { get; set; }
    }
}
