//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbmodel11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapstoneMVCAPPDBEntities : DbContext
    {
        public CapstoneMVCAPPDBEntities()
            : base("name=CapstoneMVCAPPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CastingDirector> CastingDirectors { get; set; }
        public virtual DbSet<EthinicOrigin> EthinicOrigins { get; set; }
        public virtual DbSet<FamilyMember> FamilyMembers { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Talent> Talents { get; set; }
    }
}
