//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01___CP_DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Talent()
        {
            this.Addresses = new HashSet<Address>();
            this.Cars = new HashSet<Car>();
            this.Skills = new HashSet<Skill>();
        }
    
        public int PKTalent_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string HomePhoneNum { get; set; }
        public string CellPhoneNum { get; set; }
        public string BirthDate { get; set; }
        public string Gender { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public string EyeColor { get; set; }
        public string HairColor { get; set; }
        public string UnionStatus { get; set; }
        public string SIN { get; set; }
        public int AdminPKAmin_ID { get; set; }
        public int EthinicOriginPK_EO_ID { get; set; }
        public int LoginLogin_ID { get; set; }
        public string NumOfRequest { get; set; }
        public string NumOfHired { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual EthinicOrigin EthinicOrigin { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
